### ISSUE TITLE
jscode = open('MemoryBreakPoint.js', 'r').read()

### ISSUE THREAD

**Issue by liang-android** [asmjmp0/fridaMemoryAccessTrace#2]
这句错误了吧 
应该是
jscode = open('MemoryBreakPoint.js', 'r', encoding='utf-8').read()

**Comment by liang-android** [comment]
还有问题测试的apk 无法安装

**Comment by asmjmp0** [comment]
确实，可以自己写个程序测试一下，目前只支持32位，有时间会把代码重构完善一下。
