### ISSUE TITLE
请问可以获得应用的所有内存访问序列吗？

### ISSUE THREAD

**Issue by DingcuiYu** [asmjmp0/fridaMemoryAccessTrace#4]
我想要获得某应用访问内存的序列，例如” PC R/W 内存地址“这种格式的。请问通过这个工具可能获得吗？

**Comment by asmjmp0** [comment]
不太懂你说的意思，能不能举例说明？

**Comment by DingcuiYu** [comment]
例如某个应用运行的过程中CPU通过Load/Store读了地址0x1的数据，写了地址0x2的数据，可以通过这个工具捕获到吗？

**Comment by asmjmp0** [comment]
这个工具不行，这个工具只能对某片地址的访问进行trace，以Linux系统，arm64架构为例，如果需要对指令级别进行trace这里可以给出两种解决方案：
1. 对于能进入调试状态的程序，使目标进程进入调试状态，单步调试，trace指令，过滤ldr,str指令，对于lldb调试器参考[https://github.com/yangyss/lldb-trace](https://github.com/yangyss/lldb-trace)
2. 对于不能进入调试状态的程序，且没有加固的程序，可以使用二进制插桩技术，程序.text段的全部ldr,str指令进行hook插桩。
注意，对于多线程需要对线程的访问序列进行过滤。
